[package]
name = "iter-solver"
version = "0.2.0"
edition = "2024"
license = "MIT"
description = "A rust crate provide flexible and general iterative algorithm framework." 
repository = "https://github.com/Y-S-Xing/iter-solver"

[dependencies]
thiserror = "2"